name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup & Test
        uses: docker://metaskills/lambcicd-build-ruby2.5-nodejs8.10:v2
        with:
          args: ./bin/setup; ./bin/test
