name: CI/CD
on: [push]
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: DEBUG
        run: |
          echo GITHUB_ACTION
          echo $GITHUB_ACTION
          echo GITHUB_SHA
          echo $GITHUB_SHA
          echo PWD
          echo $PWD
          cd ..
          ls -lAGp .
          mkdir 'new-stuff'
          ls -lAGp .
          which rsync
      - name: Commit
        run: |
          echo 'test'
