name: CI/CD
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup & Test
        uses: docker://metaskills/lambcicd-build-ruby2.5-nodejs8.10:v2
        with:
          args: ./bin/test-ci
  Deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy
        uses: docker://metaskills/lambcicd-build-ruby2.5-nodejs8.10:v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        with:
          args: env



# if: github.event_name == 'pull_request'
